'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("projet_test.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property agent_accueil03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agent_accueil03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property características_de_china() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("características-de-china", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChefchaouenMorocco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChefchaouenMorocco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property daa_podcast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("daa-podcast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property future_of_recruiting_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("future-of-recruiting-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grece_Santorini1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grece_Santorini1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_belgaimage_153535230_1_5f5f9e0e7cc6d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_belgaimage-153535230_1_5f5f9e0e7cc6d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italie_ville_venise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italie-ville-venise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mes_bisous_et_câlins6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mes bisous et câlins6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plaza_de_espana_sevilha_1024x642() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plaza-de-espana-sevilha-1024x642", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restaurant_hotel_lesirenuse_positano_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restaurant-hotel-lesirenuse-positano-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sad_man() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sad-man", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sky_series_collection_hdri_atmospheres_3d_model() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sky-series-collection-hdri-atmospheres-3d-model", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Turismo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turismo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property turquie_ville_istanbul_mosquee_bateaux_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("turquie-ville-istanbul-mosquee-bateaux-1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property turquie_ville_istanbul_mosquee_bateaux_1920x10801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("turquie-ville-istanbul-mosquee-bateaux-1920x10801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voyage_en_avion_on_connait_l_astuce_pour_faire_le_voyage_le_plus_agreable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voyage-en-avion-on-connait-l-astuce-pour-faire-le-voyage-le-plus-agreable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voyage_en_avion_on_connait_l_astuce_pour_faire_le_voyage_le_plus_agreable1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voyage-en-avion-on-connait-l-astuce-pour-faire-le-voyage-le-plus-agreable1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
